apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: juicefs
type: Opaque
stringData:
  name: juicefs-vol
  metaurl: "postgres://juicefs:juicefs-pass@10.233.4.87:5432/juicefs?sslmode=disable"
  storage: file
  bucket: /mnt/juicefs
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs-sc
provisioner: csi.juicefs.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: juicefs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: juicefs
  csi.storage.k8s.io/node-publish-secret-name: juicefs-secret
  csi.storage.k8s.io/node-publish-secret-namespace: juicefs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-pvc
  namespace: juicefs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: juicefs-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juicefs-app
  namespace: juicefs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juicefs-app
  template:
    metadata:
      labels:
        app: juicefs-app
    spec:
      containers:
      - name: app
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            echo "$(date -u) from $(hostname)" >> /data/out.txt;
            sleep 5;
          done
        volumeMounts:
        - name: juicefs-vol
          mountPath: /data
      volumes:
      - name: juicefs-vol
        persistentVolumeClaim:
          claimName: juicefs-pvc

