apiVersion: v1
kind: Namespace
metadata:
  name: juicefs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: juicefs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: juicefs
        - name: POSTGRES_USER
          value: juicefs
        - name: POSTGRES_PASSWORD
          value: juicefs-pass
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        hostPath:
          path: /data/postgres   # 宿主机上的目录，持久化位置
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: juicefs
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP

