apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: juicefs
  labels:
    # 增加该标签以启用认证信息校验
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: juicefs-vol
  metaurl: "postgres://juicefs:juicefs-pass@10.233.5.73:5432/juicefs?sslmode=disable"   # 数据库地址
  storage: s3
  bucket: http://myminio-hl.minio.svc.cluster.local:9000/lwj-bucket  # 存储桶地址
  access-key: 756uLvijiSFLWyhrAn0n  # 访问密钥, 在minio中创建
  secret-key: ZvXw116FFrAuBharqyuSO6NAfjSgWiFfzICrKXry  # 密钥, 在minio中创建
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs-sc
provisioner: csi.juicefs.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: juicefs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: juicefs
  csi.storage.k8s.io/node-publish-secret-name: juicefs-secret
  csi.storage.k8s.io/node-publish-secret-namespace: juicefs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-pvc
  namespace: juicefs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10G
  storageClassName: juicefs-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juicefs-app
  namespace: juicefs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juicefs-app
  template:
    metadata:
      labels:
        app: juicefs-app
    spec:
      containers:
      - name: app
        image: registry.cn-hangzhou.aliyuncs.com/liwenjian123/busybox:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            echo "$(date -u) from $(hostname)" >> /data/out.txt;
            sleep 5;
          done
        volumeMounts:
        - name: juicefs-vol
          mountPath: /data
      volumes:
      - name: juicefs-vol
        persistentVolumeClaim:
          claimName: juicefs-pvc
